ALTER TABLE `User`
  MODIFY `credits` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `subscriptionPlan` VARCHAR(191) NOT NULL DEFAULT 'FREE',
  ADD COLUMN `subscriptionExpiresAt` DATETIME(3) NULL,
  ADD COLUMN `freeCvGenerationsUsed` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `freeSelfImprovementUsed` INTEGER NOT NULL DEFAULT 0;
